version: "3.6"
volumes:
    shared-workspace:
        name: "file-system"
        driver: "local"
services:
    spark-master:
        image: beayag/trabalho-spark-master
        container_name: spark-master
        ports:
            - 8080:8080
            - 7077:7077
        volumes:
            - shared-workspace:/opt/workspace
    spark-worker-1:
        image: beayag/trabalho-spark-worker
        container_name: spark-worker-1
        environment:
            - SPARK_WORKER_CORES=4
            - SPARK_WORKER_MEMORY=1024m
        ports:
            - 8081:8081
        volumes:
            - shared-workspace:/opt/workspace
        depends_on:
            - spark-master
    spark-worker-2:
        image: beayag/trabalho-spark-worker
        container_name: spark-worker-2
        environment:
            - SPARK_WORKER_CORES=4
            - SPARK_WORKER_MEMORY=1024m
        ports:
            - 8082:8081
        volumes:
            - shared-workspace:/opt/workspace
        depends_on:
            - spark-master
    spark-worker-3:
        image: beayag/trabalho-spark-worker
        container_name: spark-worker-3
        environment:
            - SPARK_WORKER_CORES=4
            - SPARK_WORKER_MEMORY=1024m
        ports:
            - 8083:8081
        volumes:
            - shared-workspace:/opt/workspace
        depends_on:
            - spark-master
    spark-worker-4:
        image: beayag/trabalho-spark-worker
        container_name: spark-worker-4
        environment:
            - SPARK_WORKER_CORES=4
            - SPARK_WORKER_MEMORY=1024m
        ports:
            - 8084:8081
        volumes:
            - shared-workspace:/opt/workspace
        depends_on:
            - spark-master
    jupyter:
        image: beayag/trabalho-jupyter-s3
        container_name: jupyter
        ports:
            - 8888:8888
        volumes:
            - shared-workspace:/opt/workspace